<?php return array (
  'plugins.all' => 
  array (
    'layerok\\basecode' => 'layerok/basecode',
    'layerok\\posterpos' => 'layerok/posterpos',
    'layerok\\restapi' => 'layerok/restapi',
    'layerok\\telegram' => 'layerok/telegram',
    'layerok\\tgmall' => 'layerok/tgmall',
    'october\\demo' => 'october/demo',
    'offline\\mall' => 'offline/mall',
    'rainlab\\builder' => 'rainlab/builder',
    'rainlab\\location' => 'rainlab/location',
    'rainlab\\translate' => 'rainlab/translate',
    'rainlab\\user' => 'rainlab/user',
    'reazzon\\jwtauth' => 'reazzon/jwtauth',
  ),
  'modules.all' => 
  array (
    0 => 'System',
    1 => 'Backend',
    2 => 'Cms',
    3 => 'Editor',
    4 => 'Media',
    6 => 'Tailor',
  ),
  'sites.all' => 
  array (
    0 => 
    array (
      'id' => 1,
      'name' => 'Primary',
      'code' => 'primary',
      'sort_order' => 1,
      'is_custom_url' => 0,
      'app_url' => '',
      'theme' => '',
      'locale' => 'uk',
      'timezone' => '',
      'is_restricted' => 0,
      'allow_hosts' => '[[]]',
      'is_prefixed' => 0,
      'route_prefix' => '',
      'is_styled' => 0,
      'color_foreground' => NULL,
      'color_background' => NULL,
      'is_primary' => 1,
      'is_enabled' => 1,
      'is_enabled_edit' => 1,
      'created_at' => '2023-02-22 07:49:25',
      'updated_at' => '2023-02-22 09:20:34',
    ),
    1 => 
    array (
      'id' => 2,
      'name' => 'Secondary',
      'code' => 'russian',
      'sort_order' => 2,
      'is_custom_url' => 0,
      'app_url' => '',
      'theme' => '',
      'locale' => 'ru',
      'timezone' => '',
      'is_restricted' => 0,
      'allow_hosts' => '[[]]',
      'is_prefixed' => 1,
      'route_prefix' => '/ru',
      'is_styled' => 0,
      'color_foreground' => NULL,
      'color_background' => NULL,
      'is_primary' => 0,
      'is_enabled' => 1,
      'is_enabled_edit' => 1,
      'created_at' => '2023-02-22 09:19:18',
      'updated_at' => '2023-02-22 09:20:44',
    ),
  ),
);